import type { Combo, Provider, Workflow } from "./types";

function hoursFromNow(h: number): number {
  return Date.now() + h * 3600_000;
}

const ANTHROPIC_CACHE = { cacheReadMult: 0.1, cacheWriteMult: 1.25, cacheMinTokens: 1024 };
const OPENAI_CACHE = { cacheReadMult: 0.5, cacheWriteMult: 1, cacheMinTokens: 1024 };
const XAI_CACHE = { cacheReadMult: 0.25, cacheWriteMult: 1, cacheMinTokens: 1024 };
const GOOGLE_CACHE = { cacheReadMult: 0.25, cacheWriteMult: 1, cacheMinTokens: 1024 };
const NO_CACHE = { cacheReadMult: 1, cacheWriteMult: 1, cacheMinTokens: 1_000_000 };

export function seedProviders(): Provider[] {
  return [
    {
      id: "claude-code",
      name: "Claude Code",
      vendor: "Anthropic",
      tier: "subscription",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 420,
      quotaUsed: 0.62,
      quotaResetAt: hoursFromNow(5.4),
      rpm: 8,
      rpmCap: 40,
      usedCount: 184,
      models: [
        {
          id: "claude-sonnet",
          name: "Sonnet 4.5",
          context: 200_000,
          inputPerM: 3,
          outputPerM: 15,
          quality: 9,
          ...ANTHROPIC_CACHE,
        },
      ],
      notes: "OAuth subscription. Drain first. Best KV discount (10% cache reads).",
    },
    {
      id: "codex",
      name: "Codex",
      vendor: "OpenAI",
      tier: "subscription",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 510,
      quotaUsed: 0.81,
      quotaResetAt: hoursFromNow(2.1),
      rpm: 12,
      rpmCap: 30,
      usedCount: 220,
      models: [
        {
          id: "gpt-codex",
          name: "GPT Codex",
          context: 128_000,
          inputPerM: 2.5,
          outputPerM: 10,
          quality: 8,
          ...OPENAI_CACHE,
        },
      ],
      notes: "IDE subscription. High quota pressure — reset-aware routing helps.",
    },
    {
      id: "gemini-cli",
      name: "Gemini CLI",
      vendor: "Google",
      tier: "subscription",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 380,
      quotaUsed: 0.34,
      quotaResetAt: hoursFromNow(11),
      rpm: 6,
      rpmCap: 60,
      usedCount: 96,
      models: [
        {
          id: "gemini-pro",
          name: "Gemini Pro",
          context: 1_000_000,
          inputPerM: 1.25,
          outputPerM: 5,
          quality: 8,
          ...GOOGLE_CACHE,
        },
      ],
      notes: "Huge context window. Overflow relay target.",
    },
    {
      id: "copilot",
      name: "GitHub Copilot",
      vendor: "GitHub",
      tier: "subscription",
      enabled: true,
      healthy: true,
      circuit: "half",
      cooldownUntil: Date.now() + 12_000,
      latencyMs: 640,
      quotaUsed: 0.91,
      quotaResetAt: hoursFromNow(1.2),
      rpm: 18,
      rpmCap: 20,
      usedCount: 310,
      models: [
        {
          id: "copilot-gpt",
          name: "Copilot GPT",
          context: 64_000,
          inputPerM: 0,
          outputPerM: 0,
          quality: 7,
          ...NO_CACHE,
        },
      ],
      notes: "Near cap. Circuit half-open after 429s.",
    },
    {
      id: "glm",
      name: "GLM Coding",
      vendor: "Zhipu",
      tier: "cheap",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 290,
      quotaUsed: 0.22,
      quotaResetAt: hoursFromNow(20),
      rpm: 4,
      rpmCap: 80,
      usedCount: 64,
      models: [
        {
          id: "glm-4.5",
          name: "GLM 4.5",
          context: 128_000,
          inputPerM: 0.6,
          outputPerM: 2.2,
          quality: 7,
          ...OPENAI_CACHE,
        },
      ],
      notes: "Tier-2 spill. Strong coding, cheap input.",
    },
    {
      id: "minimax",
      name: "MiniMax",
      vendor: "MiniMax",
      tier: "cheap",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 310,
      quotaUsed: 0.18,
      quotaResetAt: hoursFromNow(18),
      rpm: 3,
      rpmCap: 60,
      usedCount: 41,
      models: [
        {
          id: "minimax-m2",
          name: "MiniMax M2",
          context: 200_000,
          inputPerM: 0.2,
          outputPerM: 1.1,
          quality: 7,
          ...OPENAI_CACHE,
        },
      ],
      notes: "Lowest paid input among coding models.",
    },
    {
      id: "kimi",
      name: "Kimi",
      vendor: "Moonshot",
      tier: "cheap",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 360,
      quotaUsed: 0.47,
      quotaResetAt: hoursFromNow(9),
      rpm: 5,
      rpmCap: 40,
      usedCount: 77,
      models: [
        {
          id: "kimi-k2",
          name: "Kimi K2",
          context: 256_000,
          inputPerM: 0.6,
          outputPerM: 2.5,
          quality: 8,
          ...OPENAI_CACHE,
        },
      ],
      notes: "Flat-ish monthly. Long context, good cache.",
    },
    {
      id: "deepseek",
      name: "DeepSeek",
      vendor: "DeepSeek",
      tier: "cheap",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 340,
      quotaUsed: 0.29,
      quotaResetAt: hoursFromNow(14),
      rpm: 7,
      rpmCap: 100,
      usedCount: 112,
      models: [
        {
          id: "deepseek-v3",
          name: "DeepSeek V3",
          context: 128_000,
          inputPerM: 0.27,
          outputPerM: 1.1,
          quality: 8,
          cacheReadMult: 0.1,
          cacheWriteMult: 1,
          cacheMinTokens: 1024,
        },
      ],
      notes: "Aggressive cache-read discount. Excellent spill target.",
    },
    {
      id: "groq",
      name: "Groq",
      vendor: "Groq",
      tier: "cheap",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 90,
      quotaUsed: 0.41,
      quotaResetAt: hoursFromNow(6),
      rpm: 22,
      rpmCap: 120,
      usedCount: 401,
      models: [
        {
          id: "llama-70b",
          name: "Llama 3.3 70B",
          context: 128_000,
          inputPerM: 0.05,
          outputPerM: 0.08,
          quality: 6,
          ...NO_CACHE,
        },
      ],
      notes: "Fastest. No KV discount — cheap enough that it rarely matters.",
    },
    {
      id: "xai",
      name: "xAI",
      vendor: "xAI",
      tier: "api",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 280,
      quotaUsed: 0.12,
      quotaResetAt: hoursFromNow(22),
      rpm: 2,
      rpmCap: 60,
      usedCount: 28,
      models: [
        {
          id: "grok-4.5",
          name: "Grok 4.5",
          context: 256_000,
          inputPerM: 3,
          outputPerM: 15,
          quality: 9,
          ...XAI_CACHE,
        },
      ],
      notes: "Live chat path. Cache-aware, high quality.",
    },
    {
      id: "anthropic-api",
      name: "Anthropic API",
      vendor: "Anthropic",
      tier: "api",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 400,
      quotaUsed: 0.08,
      quotaResetAt: hoursFromNow(24),
      rpm: 1,
      rpmCap: 50,
      usedCount: 19,
      models: [
        {
          id: "claude-opus",
          name: "Opus 4.5",
          context: 200_000,
          inputPerM: 15,
          outputPerM: 75,
          quality: 10,
          ...ANTHROPIC_CACHE,
        },
      ],
      notes: "Advisor / reviewer only. Never the sticky executor.",
    },
    {
      id: "openai-api",
      name: "OpenAI API",
      vendor: "OpenAI",
      tier: "api",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 430,
      quotaUsed: 0.15,
      quotaResetAt: hoursFromNow(24),
      rpm: 3,
      rpmCap: 80,
      usedCount: 44,
      models: [
        {
          id: "gpt-4.1",
          name: "GPT-4.1",
          context: 128_000,
          inputPerM: 2,
          outputPerM: 8,
          quality: 8,
          ...OPENAI_CACHE,
        },
      ],
      notes: "General API. 50% cache-read discount.",
    },
    {
      id: "iflow",
      name: "iFlow",
      vendor: "iFlow",
      tier: "free",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 720,
      quotaUsed: 0.55,
      quotaResetAt: hoursFromNow(8),
      rpm: 9,
      rpmCap: 20,
      usedCount: 130,
      models: [
        {
          id: "iflow-chat",
          name: "iFlow Chat",
          context: 32_000,
          inputPerM: 0,
          outputPerM: 0,
          quality: 5,
          ...NO_CACHE,
        },
      ],
      notes: "Free forever. Last-resort spill.",
    },
    {
      id: "qwen",
      name: "Qwen",
      vendor: "Alibaba",
      tier: "free",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 480,
      quotaUsed: 0.37,
      quotaResetAt: hoursFromNow(10),
      rpm: 5,
      rpmCap: 30,
      usedCount: 88,
      models: [
        {
          id: "qwen-plus",
          name: "Qwen Plus",
          context: 128_000,
          inputPerM: 0,
          outputPerM: 0,
          quality: 6,
          ...NO_CACHE,
        },
      ],
      notes: "Free coding-capable spill.",
    },
    {
      id: "kiro",
      name: "Kiro",
      vendor: "Kiro",
      tier: "free",
      enabled: true,
      healthy: false,
      circuit: "open",
      cooldownUntil: Date.now() + 45_000,
      latencyMs: 900,
      quotaUsed: 0.99,
      quotaResetAt: hoursFromNow(0.4),
      rpm: 0,
      rpmCap: 10,
      usedCount: 50,
      models: [
        {
          id: "kiro-free",
          name: "Kiro Free",
          context: 32_000,
          inputPerM: 0,
          outputPerM: 0,
          quality: 5,
          ...NO_CACHE,
        },
      ],
      notes: "Quota blown. Circuit open until reset.",
    },
    {
      id: "opencode",
      name: "OpenCode Free",
      vendor: "OpenCode",
      tier: "free",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 560,
      quotaUsed: 0.11,
      quotaResetAt: hoursFromNow(30),
      rpm: 2,
      rpmCap: 40,
      usedCount: 14,
      models: [
        {
          id: "opencode-free",
          name: "OpenCode Free",
          context: 64_000,
          inputPerM: 0,
          outputPerM: 0,
          quality: 5,
          ...NO_CACHE,
        },
      ],
      notes: "No-auth free tier.",
    },
    {
      id: "nim",
      name: "NVIDIA NIM",
      vendor: "NVIDIA",
      tier: "free",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 410,
      quotaUsed: 0.26,
      quotaResetAt: hoursFromNow(12),
      rpm: 4,
      rpmCap: 40,
      usedCount: 33,
      models: [
        {
          id: "nim-70b",
          name: "NIM 70B",
          context: 32_000,
          inputPerM: 0,
          outputPerM: 0,
          quality: 6,
          ...NO_CACHE,
        },
      ],
      notes: "Free hosted. Good embeddings sibling.",
    },
    {
      id: "cerebras",
      name: "Cerebras",
      vendor: "Cerebras",
      tier: "api",
      enabled: true,
      healthy: true,
      circuit: "closed",
      cooldownUntil: 0,
      latencyMs: 70,
      quotaUsed: 0.33,
      quotaResetAt: hoursFromNow(7),
      rpm: 14,
      rpmCap: 90,
      usedCount: 190,
      models: [
        {
          id: "qwen-cerebras",
          name: "Qwen 3 32B",
          context: 32_000,
          inputPerM: 0.1,
          outputPerM: 0.1,
          quality: 6,
          ...NO_CACHE,
        },
      ],
      notes: "Wafer-scale speed. /fast combo member.",
    },
  ];
}

export function seedCombos(): Combo[] {
  return [
    {
      id: "auto",
      name: "Auto",
      slug: "auto",
      strategy: "auto",
      sticky: true,
      tiers: [
        [
          { providerId: "claude-code", modelId: "claude-sonnet" },
          { providerId: "codex", modelId: "gpt-codex" },
          { providerId: "gemini-cli", modelId: "gemini-pro" },
        ],
        [
          { providerId: "glm", modelId: "glm-4.5" },
          { providerId: "deepseek", modelId: "deepseek-v3" },
          { providerId: "minimax", modelId: "minimax-m2" },
        ],
        [
          { providerId: "qwen", modelId: "qwen-plus" },
          { providerId: "iflow", modelId: "iflow-chat" },
          { providerId: "opencode", modelId: "opencode-free" },
        ],
      ],
    },
    {
      id: "coding",
      name: "Coding",
      slug: "coding",
      strategy: "fill-first",
      sticky: true,
      tiers: [
        [
          { providerId: "claude-code", modelId: "claude-sonnet" },
          { providerId: "codex", modelId: "gpt-codex" },
        ],
        [
          { providerId: "glm", modelId: "glm-4.5" },
          { providerId: "kimi", modelId: "kimi-k2" },
        ],
        [{ providerId: "qwen", modelId: "qwen-plus" }],
      ],
    },
    {
      id: "cheap",
      name: "Cheap",
      slug: "cheap",
      strategy: "cost-optimized",
      sticky: false,
      tiers: [
        [
          { providerId: "minimax", modelId: "minimax-m2" },
          { providerId: "deepseek", modelId: "deepseek-v3" },
          { providerId: "groq", modelId: "llama-70b" },
        ],
        [{ providerId: "glm", modelId: "glm-4.5" }],
        [
          { providerId: "iflow", modelId: "iflow-chat" },
          { providerId: "opencode", modelId: "opencode-free" },
        ],
      ],
    },
    {
      id: "fast",
      name: "Fast",
      slug: "fast",
      strategy: "p2c",
      sticky: false,
      tiers: [
        [
          { providerId: "groq", modelId: "llama-70b" },
          { providerId: "cerebras", modelId: "qwen-cerebras" },
        ],
        [{ providerId: "minimax", modelId: "minimax-m2" }],
        [{ providerId: "nim", modelId: "nim-70b" }],
      ],
    },
    {
      id: "cache",
      name: "Cache",
      slug: "cache",
      strategy: "cache-optimized",
      sticky: true,
      tiers: [
        [
          { providerId: "claude-code", modelId: "claude-sonnet" },
          { providerId: "anthropic-api", modelId: "claude-opus" },
        ],
        [
          { providerId: "deepseek", modelId: "deepseek-v3" },
          { providerId: "xai", modelId: "grok-4.5" },
        ],
        [{ providerId: "kimi", modelId: "kimi-k2" }],
      ],
    },
    {
      id: "advisor",
      name: "Advisor",
      slug: "advisor",
      strategy: "pipeline",
      sticky: true,
      tiers: [
        [{ providerId: "glm", modelId: "glm-4.5" }],
        [{ providerId: "claude-code", modelId: "claude-sonnet" }],
        [{ providerId: "anthropic-api", modelId: "claude-opus" }],
      ],
    },
  ];
}

export function seedWorkflows(): Workflow[] {
  return [
    {
      id: "advisor",
      name: "Advisor",
      blurb: "Sticky cheap executor. Strong model sees a summary, never the full prefix — executor KV stays hot.",
      steps: [
        {
          id: "exec",
          role: "Executor",
          agent: "glm-worker",
          sticky: true,
          comboId: "cheap",
          handoff: "full",
        },
        {
          id: "review",
          role: "Advisor",
          agent: "opus-review",
          sticky: false,
          comboId: "cache",
          handoff: "advisor",
        },
      ],
    },
    {
      id: "pipeline",
      name: "Plan · build · check",
      blurb: "Three-step pipeline. Planner and reviewer take summaries; builder keeps the long prefix.",
      steps: [
        {
          id: "plan",
          role: "Planner",
          agent: "flash-plan",
          sticky: false,
          comboId: "fast",
          handoff: "summary",
        },
        {
          id: "build",
          role: "Builder",
          agent: "sonnet-build",
          sticky: true,
          comboId: "coding",
          handoff: "full",
        },
        {
          id: "check",
          role: "Reviewer",
          agent: "opus-check",
          sticky: false,
          comboId: "advisor",
          handoff: "advisor",
        },
      ],
    },
    {
      id: "fusion",
      name: "Fusion panel",
      blurb: "Fan-out to two coding models, judge picks. Burns tokens; use on hard calls only.",
      steps: [
        {
          id: "a",
          role: "Panel A",
          agent: "sonnet",
          sticky: false,
          comboId: "coding",
          handoff: "full",
        },
        {
          id: "b",
          role: "Panel B",
          agent: "kimi",
          sticky: false,
          comboId: "cheap",
          handoff: "full",
        },
        {
          id: "judge",
          role: "Judge",
          agent: "grok-judge",
          sticky: false,
          comboId: "auto",
          handoff: "summary",
        },
      ],
    },
    {
      id: "relay",
      name: "Context relay",
      blurb: "When the executor window fills, hand the prefix to Gemini’s 1M context without resetting the thread.",
      steps: [
        {
          id: "exec",
          role: "Executor",
          agent: "codex",
          sticky: true,
          comboId: "coding",
          handoff: "full",
        },
        {
          id: "relay",
          role: "Relay",
          agent: "gemini-1m",
          sticky: true,
          comboId: "auto",
          handoff: "full",
        },
      ],
    },
  ];
}
