/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as CompressRouteImport } from './routes/compress'
import { Route as GatewayRouteImport } from './routes/gateway'
import { Route as LogRouteImport } from './routes/log'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as WorkflowsRouteImport } from './routes/workflows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressRoute = CompressRouteImport.update({
  id: '/compress',
  path: '/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRoute = GatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/combos': typeof CombosRoute
  '/compress': typeof CompressRoute
  '/gateway': typeof GatewayRoute
  '/log': typeof LogRoute
  '/providers': typeof ProvidersRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/combos': typeof CombosRoute
  '/compress': typeof CompressRoute
  '/gateway': typeof GatewayRoute
  '/log': typeof LogRoute
  '/providers': typeof ProvidersRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/combos': typeof CombosRoute
  '/compress': typeof CompressRoute
  '/gateway': typeof GatewayRoute
  '/log': typeof LogRoute
  '/providers': typeof ProvidersRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cache'
    | '/combos'
    | '/compress'
    | '/gateway'
    | '/log'
    | '/providers'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cache'
    | '/combos'
    | '/compress'
    | '/gateway'
    | '/log'
    | '/providers'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/cache'
    | '/combos'
    | '/compress'
    | '/gateway'
    | '/log'
    | '/providers'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CacheRoute: typeof CacheRoute
  CombosRoute: typeof CombosRoute
  CompressRoute: typeof CompressRoute
  GatewayRoute: typeof GatewayRoute
  LogRoute: typeof LogRoute
  ProvidersRoute: typeof ProvidersRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress': {
      id: '/compress'
      path: '/compress'
      fullPath: '/compress'
      preLoaderRoute: typeof CompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CacheRoute: CacheRoute,
  CombosRoute: CombosRoute,
  CompressRoute: CompressRoute,
  GatewayRoute: GatewayRoute,
  LogRoute: LogRoute,
  ProvidersRoute: ProvidersRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
